// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Fallback values ensure the published build never crashes if env vars are
// missing from the deploy pipeline. The anon (publishable) key is safe to
// embed in client-side code.
const FALLBACK_SUPABASE_URL = "https://ivbmlledoamqtzqpcvzl.supabase.co";
const FALLBACK_SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2Ym1sbGVkb2FtcXR6cXBjdnpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc1NjgzODQsImV4cCI6MjA5MzE0NDM4NH0.-7GJRDAHcH0rweTsBrLFL5Ro_1MPAsj6Kq0paxUpVfc";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || FALLBACK_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || FALLBACK_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
